### ISSUE TITLE
Standard flreconstruct pipeline - explanation

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/starterkit#4]
We need to

- [ ] Make sure that the current Falaise has an up to date pipeline as standard, including alpha finder and gamma tracking if appropriate (#3) and that the tutorial (#1) points at that pipeline.
- [ ] Document the options and why they are set to what they are/why you would or would not change them.
- [ ] Document alpha finder options if we consider that to be part of the main package (#3). Who should we ask about this (People who wrote it have left)? @lecdawson ?
- [ ] Document gamma tracking options if we consider that to be part of the main package (#3). Contact is probably @Tedjditi

**Comment by cherylepatrick** [comment]
See issue #12
